name: Workflow Example

on:
  push:
    branches:
      - action_b

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Decir hola
              run: echo "Hola, mundo!"

            - name: Decir adios
              run: echo ADIOS
